config/routes.rb
Rails.application.routes.draw do

  root  'pages#index'
  #root 'users#index'
  
  
  # resources :orders
  # resources :cake_prices
  resources :cakes
  resources :flavors
  resources :users
  resources :cake_orders
  resources :sessions
  
  # post '/session/:id/edit', to: 'sessions#edit'
  # post "/sessions/:id/edit"=> "sessions#edit"
  # get "/sessions/:id/edit" => "sessions#edit"
  
  get "/cake_orders/:id/previous"=> "cake_orders#previous"
  post "/cake_orders/createOrder"=>"cake_orders#createOrder"
  get "/users/deleteAllUsers" => "users#deleteAllUsers"
  get "/contacts/"=> "contacts#index"
  get "/pages/:page" => "pages#show"
  post   '/login'   => 'sessions#create'
  # get '/users/signout' => 'users#signout'
  # post '/users/signout', to: 'users#signout'
  #get '/sessions/admin_test' => 'sessions#admin_test'
  post '/sessions/admin_test', to: 'sessions#admin_test'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, optional:true
  belongs_to :cakePrice, optional:true
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:user_id, :orderDate, :deliveryDate, :deliveryAddress, :deliveryPhone, :status, :comments, :cakePrice_id, :paidStatus)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.haml
= form_for @order do |f|
  - if @order.errors.any?
    #error_explanation
      %h2= "#{pluralize(@order.errors.count, "error")} prohibited this order from being saved:"
      %ul
        - @order.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :orderDate
  
  .field
    = f.label :deliveryDate
    = f.datetime_select :deliveryDate
  .field
    = f.label :deliveryAddress
    = f.text_area :deliveryAddress
  .field
    = f.label :deliveryPhone
    = f.text_field :deliveryPhone
  .field
    = f.label :status
    = f.number_field :status
  .field
    = f.label :comments
    = f.text_area :comments
  .field
    = f.label :cakePrice
    = f.text_field :cakePrice
  .field
    = f.label :paidStatus
    = f.number_field :paidStatus
  .actions
    = f.submit 'Save'

app/views/orders/edit.html.haml
%h1 Editing order

= render 'form'

= link_to 'Show', @order
\|
= link_to 'Back', orders_path

app/views/orders/index.html.haml
%html
  %body
    %meta{:charset => "UTF-8"}/
    %meta{:content => "", :name => "description"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
    %title BerryDeli Cakes/orders
    %link{:href => "img/core-img/favicon.ico", :rel => "icon"}/
    %link{:href => "style.css", :rel => "stylesheet"}/
    %link{:href => "css/responsive/responsive.css", :rel => "stylesheet"}/
    #preloader
      .yummy-load
    #pattern-switcher
      Shopping Cart
    .top_header_area
      .container
        .row
          .col-5.col-sm-6
            .top_social_bar
              %a{:href => "#"}
                %i.fa.fa-facebook{"aria-hidden" => "true"}
          .col-7.col-sm-6
            .signup-search-area.d-flex.align-items-center.justify-content-end
              .login_register_area.d-flex
                .login
                  %a#loginLink{"data-target" => "#loginModal", "data-toggle" => "modal", :href => "#"} Sign in
                .register
                  %a#registerLink{"data-target" => "#registerModal", "data-toggle" => "modal", :href => "#"} Sign up
              .search_button
                %a.searchBtn{:href => "#"}
                  %i.fa.fa-search{"aria-hidden" => "true"}
              .search-hidden-form
                %form{:action => "#", :method => "get"}
                  %input#search-anything{:name => "search", :placeholder => "What would you like?", :type => "search"}/
                  %input.d-none{:type => "submit", :value => ""}/
                  %span.searchBtn
                    %i.fa.fa-times{"aria-hidden" => "true"}
    %header.header_area
      .container
        .row
          .col-12
            .logo_area.text-center
              %a.yummy-logo{:href => "index.html"} BerryDeli Cakes
        .row
          .col-12
            %nav.navbar.navbar-expand-lg
              %button.navbar-toggler{"aria-controls" => "yummyfood-nav", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#yummyfood-nav", "data-toggle" => "collapse", :type => "button"}
                %i.fa.fa-bars{"aria-hidden" => "true"}
                Menu
              #yummyfood-nav.collapse.navbar-collapse.justify-content-center
                %ul#yummy-nav.navbar-nav
                  %li.nav-item
                    %a.nav-link{:href => "index.html"}
                      Home
                      %span.sr-only (current)
                  %li.nav-item
                    %a.nav-link{:href => "archive.html"} Previous Designs
                  %li.nav-item
                    %a.nav-link{:href => "flavors.html"} Flavors
                  %li.nav-item
                    %a.nav-link{:href => "contact.html"} Contact Me
    .breadcumb-area{:style => "background-image: url(img/bg-img/breadcumb.jpg);"}
      .container.h-100
        .row.h-100.align-items-center
          .col-12
            .bradcumb-title.text-center
              %h2 Orders
    .breadcumb-nav
      .container
        .row
          .col-12
            %nav{"aria-label" => "breadcrumb"}
              %ol.breadcrumb
                %li.breadcrumb-item
                  %a{:href => "index.html"}
                    %i.fa.fa-home{"aria-hidden" => "true"}
                    Home
                %li.breadcrumb-item.active{"aria-current" => "page"} Flavors
    %section.archive-area.section_padding_80
    .container
      .row
      
     
       
         
        
        
        
        
        
        
        
        // - @flavors.each_with_index do |flavor, index|
        //   .col-12.col-md-6.col-lg-4
        //     .single-post.wow.fadeInUp{"data-wow-delay" => "0.2s"}
        //       .post-thumb
        //         //%img.img-thumbnail{:src => File.join(".","flavorsUploads",flavor.flavorImgURL), :height=>"150px"}/      VISH
        //         // =link_to  do flavor end
        //       .post-content
        //         %h4.post-headline= flavor.name

    #portfolio.instargram_area.owl-carousel.section_padding_100_0.clearfix
    
      .instagram_gallery_item
        
        %img{:alt => "", :src => "img/instagram-img/1.jpg"}/

        .hover_overlay
          .yummy-table
            .yummy-table-cell
              .follow-me.text-center
                %a{:href => "#"}
                  %i.fa.fa-facebook{"aria-hidden" => "true"}
                  Like me
    
      .instagram_gallery_item
        
        %img{:alt => "", :src => "img/instagram-img/2.jpg"}/

        .hover_overlay
          .yummy-table
            .yummy-table-cell
              .follow-me.text-center
                %a{:href => "#"}
                  %i.fa.fa-facebook{"aria-hidden" => "true"}
                  Like me
    
      .instagram_gallery_item
        
        %img{:alt => "", :src => "img/instagram-img/3.jpg"}/

        .hover_overlay
          .yummy-table
            .yummy-table-cell
              .follow-me.text-center
                %a{:href => "#"}
                  %i.fa.fa-facebook{"aria-hidden" => "true"}
                  Like me
    
      .instagram_gallery_item
        
        %img{:alt => "", :src => "img/instagram-img/4.jpg"}/

        .hover_overlay
          .yummy-table
            .yummy-table-cell
              .follow-me.text-center
                %a{:href => "#"}
                  %i.fa.fa-facebook{"aria-hidden" => "true"}
                  Like me
    
      .instagram_gallery_item
        
        %img{:alt => "", :src => "img/instagram-img/5.jpg"}/

        .hover_overlay
          .yummy-table
            .yummy-table-cell
              .follow-me.text-center
                %a{:href => "#"}
                  %i.fa.fa-facebook{"aria-hidden" => "true"}
                  Like me
    
      .instagram_gallery_item
        
        %img{:alt => "", :src => "img/instagram-img/6.jpg"}/
        .hover_overlay
          .yummy-table
            .yummy-table-cell
              .follow-me.text-center
                %a{:href => "#"}
                  %i.fa.fa-facebook{"aria-hidden" => "true"}
                  Like me
      .instagram_gallery_item
        %img{:alt => "", :src => "img/instagram-img/1.jpg"}/
        .hover_overlay
          .yummy-table
            .yummy-table-cell
              .follow-me.text-center
                %a{:href => "#"}
                  %i.fa.fa-facebook{"aria-hidden" => "true"}
                  Like me
      .instagram_gallery_item
        %img{:alt => "", :src => "img/instagram-img/2.jpg"}/
        .hover_overlay
          .yummy-table
            .yummy-table-cell
              .follow-me.text-center
                %a{:href => "#"}
                  %i.fa.fa-facebook{"aria-hidden" => "true"}
                  Like me
    .social_icon_area.clearfix
      .container
        .row
          .col-12
            .footer-social-area.d-flex
              .single-icon
                %a{:href => "#"}
                  %i.fa.fa-facebook{"aria-hidden" => "true"}
                  %span facebook
    %footer.footer_area
      .container
        .row
          .col-12
            .footer-content
              .footer-logo-area.text-center
                %a.yummy-logo{:href => "index.html"} BerryDeli Cakes
              %nav.navbar.navbar-expand-lg
                %button.navbar-toggler{"aria-controls" => "yummyfood-footer-nav", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#yummyfood-footer-nav", "data-toggle" => "collapse", :type => "button"}
                  %i.fa.fa-bars{"aria-hidden" => "true"}
                  Menu
                #yummyfood-footer-nav.collapse.navbar-collapse.justify-content-center
                  %ul.navbar-nav
                    %li.nav-item.active
                      %a.nav-link{:href => "#"}
                        Home
                        %span.sr-only (current)
                    %li.nav-item
                      %a.nav-link{:href => "archive.html"} Previous Designs
                    %li.nav-item
                      %a.nav-link{:href => "flavors.html"} Flavors
                    %li.nav-item
                      %a.nav-link{:href => "reviews.html"} Customer Reviews
                    %li.nav-item
                      %a.nav-link{:href => "contact.html"} Contact Me
      .container
        .row
          .col-12
            .copy_right_text.text-center
              %p
                Copyright @2018 | BerryDeli Cakes
                %i.fa.fa-heart-o{"aria-hidden" => "true"}
        
    #registerModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :role => "dialog", :tabindex => "-1"}
      .modal-dialog{:role => "document"}
        .modal-content
          #registerView
            .modal-header
              %h4.modal-title Register
              %button.close{"data-dismiss" => "modal", :type => "button"}
                %span{"aria-hidden" => "true"} ×
                %span.sr-only Close
            .modal-body
              .well
                %form#registerForm{"data-toggle" => "validator"}
                  .form-group
                    %label.control-label{:for => "name"} Name
                    %input#nameR.form-control{:name => "name", :placeholder => "Name", :title => "Please enter your name", :type => "text"}/
                  .form-group
                    %label.control-label{:for => "lastname"} Lastname
                    %input#lastNameR.form-control{:name => "lastname", :placeholder => "Lastname", :title => "Please enter your lastname", :type => "text"}/
                  .form-group
                    %label.control-label{:for => "email"} E-mail
                    %input#emailR.form-control{:name => "email", :placeholder => "E-mail", :title => "Please enter your email", :type => "text"}/
                  .form-group
                    %label.control-label{:for => "phone"} Phone
                    %input#phoneR.form-control{:name => "phone", :placeholder => "Phone Number", :title => "Please enter your telephone", :type => "text"}/
                  .form-group
                    %label.control-label{:for => "address"} Address
                    %input#addressR.form-control{:name => "address", :placeholder => "Address", :title => "Please enter your address", :type => "text"}/
                  .form-group
                    %label.control-label{:for => "username"} Username
                    %input#usernameR.form-control{:name => "username", :placeholder => "Username", :required => "", :title => "Please enter your username", :type => "text"}/
                    %span.help-block
                  .form-group
                    %label.control-label{:for => "password"} Password
                    %input#passwordR.form-control{:name => "password", :placeholder => "Password", :required => "", :title => "Please enter your password", :type => "password"}/
                    %span.help-block Min. 6 characteres
                  .form-group
                    %label.control-label{:for => "password"} Confirm Password
                    %input#confirmPasswordR.form-control{:name => "passwordConfirm", :placeholder => "Confirm Password", :required => "", :title => "Confirm password", :type => "password"}/
                    %span.help-block
                  #registerErrorMsg.alert.alert-danger.collapse{:role => "alert"} Register error
                  %button.btn.contact-btn.btn-block{:type => "submit"} Register
    #loginModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :role => "dialog", :tabindex => "-1"}
      .modal-dialog{:role => "document"}
        .modal-content
          #loginView
            .modal-header
              %h4.modal-title Login
              %button.close{"data-dismiss" => "modal", :type => "button"}
                %span{"aria-hidden" => "true"} ×
                %span.sr-only Close
            .modal-body
              .well
                %form#loginForm
                  .form-group
                    %label.control-label{:for => "username"} Username
                    %input#usernameL.form-control{:name => "username", :placeholder => "Username", :required => "", :title => "Please enter your username", :type => "text"}/
                  .form-group
                    %label.control-label{:for => "password"} Password
                    %input#passwordL.form-control{:name => "password", :placeholder => "Password", :required => "", :title => "Please enter your password", :type => "password"}/
                  #loginErrorMsg.alert.alert-danger.collapse{:role => "alert"} Login error
                  %button.btn.contact-btn.btn-block{:type => "submit"} Login

    
    
    
    
    
    %script{:src => "js/jquery/jquery-2.2.4.min.js"}
    %script{:src => "js/bootstrap/popper.min.js"}
    %script{:src => "js/bootstrap/bootstrap.min.js"}
    %script{:src => "js/others/plugins.js"}
    %script{:src => "js/active.js"}















        
// %table
// %table
//   %thead
//     %tr
//       %th Name
//       %th Flavorimgurl
//       %th
//       %th
//       %th

//   %tbody
//     - @flavors.each do |flavor|
//       %tr
//         %td= flavor.name
//         %td= flavor.flavorImgURL
//         %td= link_to 'Show', flavor
//         %td= link_to 'Edit', edit_flavor_path(flavor)
//         %td= link_to 'Destroy', flavor, method: :delete, data: { confirm: 'Are you sure?' }

// %br


// %a.btn-floating.btn-lg.purple-gradient
//   %i.fa.fa-bolt

// = link_to 'New Flavor', new_flavor_path

app/views/orders/new.html.haml
%h1 New order

= render 'form'

= link_to 'Back', orders_path

app/views/orders/show.html.haml
%p#notice= notice

%p
  %b Order:
  = @order.id

%p
  %b User:
  = @order.user_id

%p
  %b Deliverydate:
  = @order.deliveryDate
%p
  %b Deliveryaddress:
  = @order.deliveryAddress
%p
  %b Deliveryphone:
  = @order.deliveryPhone
%p
  %b Status:
  = @order.status
%p
  %b Comments:
  = @order.comments
%p
  %b Cakeprice:
  = @order.cakePrice
%p
  %b Paidstatus:
  = @order.paidStatus

= link_to 'Edit', edit_order_path(@order)
\|
= link_to 'Back', orders_path